import React, { Component } from 'react'

export default class ListaDeNotas extends Component{

    render() {
        return (
            <ul>
                <li>
                    <section>
                        <header>
                            <h3>Titulo</h3>
                        </header>
        
                        <p>Escreva sua Nota</p>
                    </section>
                </li>
        
                <li>
                    <section>
                        <header>
                            <h3>Titulo</h3>
                        </header>
                        <p>Escreva sua Nota</p>
                    </section>
                </li>
        
                <li>
                    <section>
                        <header>
                            <h3>Titulo</h3>
                        </header>
                        <p>Escreva sua Nota</p>
                    </section>
                </li>
            </ul>
        );
    }
}